###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: very.angry.maciek@gmail.com
#   CREATED: 04-10-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: pybind11-test-env

  channels:
    - bioconda
    - conda-forge

  dependencies:
    - black=19.10b0
    - flake8=3.8.3
    - numpy=1.19.0
    - pip=20.2.3
    - pip:
      - cppimport==20.8.4.2
    - pybind11=2.5.0
    - python=3.7.4

...
