###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: very.angry.maciek@gmail.com
#   CREATED: 04-10-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: test-environment

  channels:
    - bioconda
    - conda-forge

  dependencies:
    - black=19.10b0
    - flake8=3.8.3
    - numpy=1.19.0
    - pybind11=2.5.0
    - python=3.7.4

...
